In [3]:
import numpy as np

# Empty array

In [4]:
ar = np.array([])
ar

array([], dtype=float64)

## Single Dimensional Array

In [5]:
ar = np.array([1,8,6])
ar

array([1, 8, 6])

# list to array

In [6]:
ls = [1,8,6,41,5]
print(ls)

ar = np.array(ls)
ar

[1, 8, 6, 41, 5]


array([ 1,  8,  6, 41,  5])

In [7]:
print(ar)

[ 1  8  6 41  5]


In [8]:
display(ar)

array([ 1,  8,  6, 41,  5])

# tuple into array

In [9]:
tp = (7,8,6,1)
print(tp)
ar = np.array(tp)
ar

(7, 8, 6, 1)


array([7, 8, 6, 1])

# set into array

In [10]:
s = {7,8,6,1,1,5}
print(s)
ar = np.array(s)
ar

{1, 5, 6, 7, 8}


array({1, 5, 6, 7, 8}, dtype=object)

# creating the array

In [11]:
ar = np.array([8,9,7,6,2])
ar

array([8, 9, 7, 6, 2])

# Data Type 

In [12]:
type(ar)

numpy.ndarray

# Element data type

In [13]:
ar.dtype

dtype('int32')

# Memory allocated to each element bytes

In [14]:
ar.itemsize

4

# Number of elements in the array

In [15]:
ar.size

5

# dimension

In [16]:
ar.ndim

1

# shape

In [17]:
ar.shape

(5,)

# User defined function

In [18]:
def array_info(ar):
    print("Dimmension of the Array:",ar.ndim)
    print("Shape of the Array:",ar.shape)
    print("Data Type:",type(ar))
    print("Number of elements in the Array:",ar.size)
    print("Elements Data Type:", ar.dtype)
    print("Memory allogation of Each Element:", ar.itemsize)
    print("Total Elements Memory allogation:", ar.nbytes)
    display(ar)

In [19]:
array_info(ar)

Dimmension of the Array: 1
Shape of the Array: (5,)
Data Type: <class 'numpy.ndarray'>
Number of elements in the Array: 5
Elements Data Type: int32
Memory allogation of Each Element: 4
Total Elements Memory allogation: 20


array([8, 9, 7, 6, 2])

In [20]:
print(ar)

[8 9 7 6 2]


## Indexing

In [21]:
import numpy as np

In [22]:
ar = np.array([8,9,7,6])

In [23]:
ar

array([8, 9, 7, 6])

In [24]:
ar[2]

7

In [25]:
ar[-2]

7

## Slicing 

In [26]:
ar

array([8, 9, 7, 6])

In [27]:
ar[:]

array([8, 9, 7, 6])

In [28]:
# : -> 0 (Start)
# : -> n-1 (End)
ar[::]

array([8, 9, 7, 6])

In [29]:
# : -> Start => index value - 0
# 2 -> n-1 => 2-1 => 1
ar[:2]

array([8, 9])

In [30]:
# 1 -> Starts at index value 1
# : -> ends at n-1
ar[1:]

array([9, 7, 6])

In [31]:
# 1 -> Starts at index value 1
# 3 -> Ends ar n-1=> 3-1=> 2
# : -> to => from 1 to 2
ar[1:3]

array([9, 7])

# Creating array with different ways

In [32]:
ar = np.zeros(5)
ar

array([0., 0., 0., 0., 0.])

In [33]:
ar = np.ones(3)
ar

array([1., 1., 1.])

In [34]:
ar = np.arange(6)
ar

array([0, 1, 2, 3, 4, 5])

In [35]:
ar = np.arange(2,6)
ar

array([2, 3, 4, 5])

In [36]:
ar = np.arange(1,9,2)
ar

array([1, 3, 5, 7])

In [37]:
ar = np.linspace(1,5,9)
ar

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [40]:
ar = np.linspace(1,5,17)
ar

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [41]:
# 1 -> starting value
# 5 -> Ending Value
# 9 -> Number of elments need to display
# note* -> intervals between all points must be equal
ar = np.linspace(1,5,10)
ar

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

## Arthematic Operations

In [42]:
ar  = np.array([1,2,3,5])
ar1 = np.array([5,2,3,2])

In [43]:
ar + ar1

array([6, 4, 6, 7])

In [44]:
ar - ar1

array([-4,  0,  0,  3])

In [45]:
ar / ar1

array([0.2, 1. , 1. , 2.5])

In [46]:
ar // ar1

array([0, 1, 1, 2])

In [47]:
ar % ar1

array([1, 0, 0, 1])

In [48]:
ar * ar1

array([ 5,  4,  9, 10])

In [49]:
ar  = np.array([1,2,3,5])
ar

array([1, 2, 3, 5])

In [50]:
np.sin(ar)

array([ 0.84147098,  0.90929743,  0.14112001, -0.95892427])

In [51]:
np.log(ar)

array([0.        , 0.69314718, 1.09861229, 1.60943791])

In [52]:
np.min(ar)

1

In [53]:
np.max(ar)

5

In [54]:
np.sum(ar)

11

In [55]:
np.mean(ar)

2.75

In [56]:
mean = np.sum(ar) / len(ar)

In [57]:
mean

2.75

In [58]:
np.sqrt(4)

2.0

In [ ]:
np.