min

max

sum

mean

Copy

View

Transpose

astype(dtype='float')

dtype='int'

Changing the data types

    -> While creating array we are changing datatype
    
    -> after creating array we are changing the datatype -> astype
    
Concatinating

hstack

vstack

ravel

flatten

ceil 

floor

split -> np.split(x, 3)

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,5,4],[8,4,5],[2,1,5]])
arr

array([[1, 5, 4],
       [8, 4, 5],
       [2, 1, 5]])

In [3]:
np.min(arr)

1

In [4]:
np.max(arr)

8

In [5]:
np.sum(arr)

35

In [6]:
np.mean(arr)

3.888888888888889

In [7]:
round(np.mean(arr),2)

3.89

## copy vs view

In [ ]:
Copy

Both variables owning data

I am having a car

You are having a car

In [ ]:
View -> Mirror

Only One Data owning by two variables

Self rental Car

You

In [8]:
arr

array([[1, 5, 4],
       [8, 4, 5],
       [2, 1, 5]])

In [9]:
arr_c = arr.copy()
arr_c

array([[1, 5, 4],
       [8, 4, 5],
       [2, 1, 5]])

In [10]:
arr_c[0,0]=7
arr_c

array([[7, 5, 4],
       [8, 4, 5],
       [2, 1, 5]])

In [11]:
arr

array([[1, 5, 4],
       [8, 4, 5],
       [2, 1, 5]])

In [12]:
arr_v = arr.view()
arr_v

array([[1, 5, 4],
       [8, 4, 5],
       [2, 1, 5]])

In [13]:
arr

array([[1, 5, 4],
       [8, 4, 5],
       [2, 1, 5]])

In [14]:
arr[0,0]=6
arr

array([[6, 5, 4],
       [8, 4, 5],
       [2, 1, 5]])

In [15]:
arr_v

array([[6, 5, 4],
       [8, 4, 5],
       [2, 1, 5]])

In [16]:
arr_v[1,2] = 7
arr_v

array([[6, 5, 4],
       [8, 4, 7],
       [2, 1, 5]])

In [17]:
arr

array([[6, 5, 4],
       [8, 4, 7],
       [2, 1, 5]])

## Transpose

In [18]:
arr.T

array([[6, 8, 2],
       [5, 4, 1],
       [4, 7, 5]])

In [ ]:
### astype(dtype='float')

### dtype='int'

In [19]:
arr

array([[6, 5, 4],
       [8, 4, 7],
       [2, 1, 5]])

In [20]:
arr.dtype

dtype('int32')

In [21]:
arr_as = arr.astype(dtype='float')
arr_as

array([[6., 5., 4.],
       [8., 4., 7.],
       [2., 1., 5.]])

In [22]:
arr_as.dtype

dtype('float64')

In [23]:
arr = np.array([[1, 2 ,3],[8, 2.6 ,5]])
arr

array([[1. , 2. , 3. ],
       [8. , 2.6, 5. ]])

In [24]:
arr = np.array([[1,2,3],[8,2.6,5]],dtype='int')
arr

array([[1, 2, 3],
       [8, 2, 5]])

In [25]:
arr = np.array([[1, '2' ,3],[8, 2.6 ,5]])
arr

array([['1', '2', '3'],
       ['8', '2.6', '5']], dtype='<U32')

In [26]:
arr_c

array([[7, 5, 4],
       [8, 4, 5],
       [2, 1, 5]])

In [27]:
arr_v

array([[6, 5, 4],
       [8, 4, 7],
       [2, 1, 5]])

In [28]:
# default axis = 0 => row base
np.concatenate([arr_c,arr_v])

array([[7, 5, 4],
       [8, 4, 5],
       [2, 1, 5],
       [6, 5, 4],
       [8, 4, 7],
       [2, 1, 5]])

In [29]:
# axis = 1 => column base
np.concatenate([arr_c,arr_v],axis=1)

array([[7, 5, 4, 6, 5, 4],
       [8, 4, 5, 8, 4, 7],
       [2, 1, 5, 2, 1, 5]])

In [30]:
# Concatenate axis =1
np.hstack((arr_c,arr_v))

array([[7, 5, 4, 6, 5, 4],
       [8, 4, 5, 8, 4, 7],
       [2, 1, 5, 2, 1, 5]])

In [31]:
# Concatenate axis =0
np.vstack((arr_c,arr_v))

array([[7, 5, 4],
       [8, 4, 5],
       [2, 1, 5],
       [6, 5, 4],
       [8, 4, 7],
       [2, 1, 5]])

In [32]:
arr_c

array([[7, 5, 4],
       [8, 4, 5],
       [2, 1, 5]])

In [33]:
# ravel converts any dimenstions into single dimensions
np.ravel(arr_c)

array([7, 5, 4, 8, 4, 5, 2, 1, 5])

In [34]:
arr_c.flatten()

array([7, 5, 4, 8, 4, 5, 2, 1, 5])

In [35]:
arr_c

array([[7, 5, 4],
       [8, 4, 5],
       [2, 1, 5]])

In [36]:
# f -> fortan style
arr_c.flatten(order='f')

array([7, 8, 2, 5, 4, 1, 4, 5, 5])

In [1]:
import numpy as np
arr = np.array([[1.99,3.6],[8.01,6.0]])
arr

array([[1.99, 3.6 ],
       [8.01, 6.  ]])

In [2]:
np.ceil(arr)

array([[2., 4.],
       [9., 6.]])

In [3]:
np.floor(arr)

array([[1., 3.],
       [8., 6.]])

In [5]:
arr_c = np.array([[1,5,4],[8,4,5],[2,1,5]])
arr = arr_c.ravel()
arr

array([1, 5, 4, 8, 4, 5, 2, 1, 5])

In [6]:
np.split(arr,9)

[array([1]),
 array([5]),
 array([4]),
 array([8]),
 array([4]),
 array([5]),
 array([2]),
 array([1]),
 array([5])]

In [ ]:
sp = np.split(arr,3)
sp

In [ ]:
sp[1]

## For more manipulations on the array

https://numpy.org/doc/stable/reference/generated/numpy.split.html

https://numpy.org/doc/stable/index.html