In [1]:
def array_info(ar):
    print("Dimmension of the Array:",ar.ndim)
    print("Shape of the Array:",ar.shape)
    print("Data Type:",type(ar))
    print("Number of elements in the Array:",ar.size)
    print("Elements Data Type:", ar.dtype)
    print("Memory allogation of Each Element:", ar.itemsize)
    print("Total Elements Memory allogation:", ar.nbytes)
    display(ar)

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,5,4],[6,5,4],[8,4,6]])
arr

array([[1, 5, 4],
       [6, 5, 4],
       [8, 4, 6]])

In [4]:
array_info(arr)

Dimmension of the Array: 2
Shape of the Array: (3, 3)
Data Type: <class 'numpy.ndarray'>
Number of elements in the Array: 9
Elements Data Type: int32
Memory allogation of Each Element: 4
Total Elements Memory allogation: 36


array([[1, 5, 4],
       [6, 5, 4],
       [8, 4, 6]])

In [5]:
arr

array([[1, 5, 4],
       [6, 5, 4],
       [8, 4, 6]])

In [6]:
arr[1,1]

5

In [7]:
arr[2,2]

6

In [8]:
arr[2,0]

8

In [9]:
arr[-2,-3]

6

In [10]:
arr

array([[1, 5, 4],
       [6, 5, 4],
       [8, 4, 6]])

In [11]:
arr[0,0]

1

In [12]:
arr[1,2]

4

In [13]:
# 0, 0
# 1, 0
arr[:2 , 0]

array([1, 6])

In [14]:
arr

array([[1, 5, 4],
       [6, 5, 4],
       [8, 4, 6]])

In [16]:
# arr[2,0], arr[2,1]

arr[2,:2]

array([8, 4])

In [18]:

# arr[1,1]  arr[1,2]
arr[1,1:]

array([5, 4])

In [17]:
arr

array([[1, 5, 4],
       [6, 5, 4],
       [8, 4, 6]])

In [19]:
# arr[0,2] arr[1,2] arr[2,2]
arr[: , 2]

array([4, 4, 6])

In [20]:
arr

array([[1, 5, 4],
       [6, 5, 4],
       [8, 4, 6]])

In [21]:
arr[1 , :]

array([6, 5, 4])

In [22]:
arr = np.array([[1,5,4],[2,6,8]])
arr

array([[1, 5, 4],
       [2, 6, 8]])

In [23]:
arr[0,1]

5

In [24]:
arr[:,1]

array([5, 6])

In [25]:
arr

array([[1, 5, 4],
       [2, 6, 8]])

In [26]:
arr[1,:2]

array([2, 6])

In [27]:
arr[:,:]

array([[1, 5, 4],
       [2, 6, 8]])

### list to 2D => reshape

In [ ]:
lst = [1,5,4,6,5,8]
arr = np.array(lst).reshape(3,2)
arr

In [ ]:
arr = np.array(lst).reshape(2,3)
arr

In [ ]:
arr = np.array(lst).reshape(1,6)
arr

In [ ]:
arr = np.array(lst).reshape(6,1)
arr

In [ ]:
lst

In [ ]:
arr = np.array(lst).reshape(2,4)
arr

In [ ]:
arr = np.array(lst).reshape(2,2)
arr

In [ ]:
import numpy as np
tpl = (4,5,3,6,5,1,2,6)
arr = np.array(tpl).reshape(2,4)
arr

In [ ]:
arr = np.zeros(6).reshape(2,3)
arr

In [ ]:
arr = np.ones(4).reshape(2,2)
arr

In [ ]:
arr = np.arange(30).reshape(5,6)
arr

In [ ]:
arr = np.arange(1,31).reshape(5,6)
arr

In [ ]:
arr = np.arange(1,22,4).reshape(2,3)
arr

In [ ]:
arr = np.linspace(1,6,12).reshape(2,6)
arr

In [ ]:
### Arthematics

In [ ]:
import numpy as np
ar  = np.array([[1,2],[3,5]])
arr = np.array([[8,3],[6,2],[4,3]])

In [ ]:
ar.shape

In [ ]:
arr.shape

In [ ]:
ar + arr

In [ ]:
ar  = np.array([[1,2],[3,5]])
arr = np.array([[8,3],[6,2]])

In [ ]:
ar + arr

In [ ]:
ar - arr

In [ ]:
ar * arr

In [ ]:
ar / arr

In [ ]:
ar // arr

In [ ]:
ar % arr

In [ ]:
ar ** arr

In [ ]:
ar

In [ ]:
arr

In [ ]:
np.sin(arr)

In [ ]:
np.cos(arr)

In [ ]:
np.log(arr)